// examples/nextjs/src/app/protected/page.tsx
// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Wojciech Polak
// src/app/protected/page.tsx

import type { Metadata } from 'next';
import React from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { protectedBadgeUrl } from 'magic-sso-example-ui';
import { verifyToken, redirectToLogin } from '@magic-link-sso/nextjs';

export const metadata: Metadata = {
  title: 'Protected | Magic Link SSO Next.js',
};

export default async function ProtectedPage(): Promise<React.JSX.Element | null> {
  const auth = await verifyToken();

  if (!auth) {
    redirectToLogin('/protected');
    return null;
  }

  return (
    <main className="shell">
      <div className="card hero">
        <div className="hero-top">
          <Image
            src={protectedBadgeUrl}
            alt="Protected area badge"
            width={144}
            height={144}
            className="badge"
            unoptimized
          />
          <div>
            <p className="eyebrow">Protected Space</p>
            <h1 className="title">Your Next.js session is locked in and verified.</h1>
            <p className="copy">
              Hello, <strong>{auth.email}</strong>. This page is available only after a valid Magic
              Link SSO token is confirmed.
            </p>
          </div>
        </div>

        <div className="meta-row">
          <section className="panel panel-dark">
            <p className="panel-title">Protected Route</p>
            <p className="panel-copy">
              This page uses the reusable <code>verifyToken()</code> and{' '}
              <code>redirectToLogin()</code> server helpers.
            </p>
          </section>

          <section className="panel">
            <p className="panel-title">Next Steps</p>
            <div className="actions">
              <Link href="/" className="button button-primary">
                Back Home
              </Link>
              <form action="/logout" method="post">
                <button type="submit" className="button button-secondary">
                  Logout
                </button>
              </form>
            </div>
          </section>
        </div>
      </div>
    </main>
  );
}

// examples/nuxt/app/pages/protected.vue
<script setup lang="ts">
import protectedBadgeUrl from 'magic-sso-example-ui/assets/protected-page-badge.svg';
import type { AuthPayload } from '@magic-link-sso/nuxt';

definePageMeta({
    middleware: ['magic-sso-auth'],
});

const authState = useState<AuthPayload | null>('protected-auth', () => null);

if (import.meta.server) {
    authState.value = await useMagicSsoAuth();
}

useHead({
    title: 'Protected | Magic Link SSO Nuxt',
});
</script>

<template>
    <main class="shell">
        <div class="card hero">
            <div class="hero-top">
                <img
                    :src="protectedBadgeUrl"
                    alt="Protected area badge"
                    class="badge"
                    width="144"
                    height="144"
                />
                <div>
                    <p class="eyebrow">Protected Space</p>
                    <h1 class="title">Your Nuxt session is locked in and verified.</h1>
                    <p class="copy">
                        Hello,
                        <strong>{{ authState?.email ?? 'friend' }}</strong
                        >. This page is available only after a valid Magic Link SSO token is
                        confirmed.
                    </p>
                </div>
            </div>

            <div class="meta-row">
                <section class="panel panel-dark">
                    <p class="panel-title">Protected Route</p>
                    <p class="panel-copy">
                        This page uses the reusable `magic-sso-auth` middleware and the
                        `useMagicSsoAuth()` server helper.
                    </p>
                </section>
                <section class="panel">
                    <p class="panel-title">Next Steps</p>
                    <div class="actions">
                        <a href="/" class="button button-primary">Back Home</a>
                        <form action="/logout" method="post">
                            <button type="submit" class="button button-secondary">Logout</button>
                        </form>
                    </div>
                </section>
            </div>
        </div>
    </main>
</template>
